
import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
  useColorScheme,
  Platform,
  Share,
  TextInput,
  Modal,
} from 'react-native';
import { colors } from '@/styles/commonStyles';
import { IconSymbol } from '@/components/IconSymbol';
import { useAuth } from '@/contexts/AuthContext';
import * as seaTimeApi from '@/utils/seaTimeApi';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';

interface ReportSummary {
  total_hours: number;
  total_days: number;
  entries_by_vessel: {
    vessel_name: string;
    total_hours: number;
  }[];
  entries_by_month: {
    month: string;
    total_hours: number;
  }[];
}

export default function ReportsScreen() {
  const colorScheme = useColorScheme();
  const isDark = colorScheme === 'dark';
  const { user, signOut } = useAuth();
  
  const [summary, setSummary] = useState<ReportSummary | null>(null);
  const [loading, setLoading] = useState(false);
  const [showTestUserModal, setShowTestUserModal] = useState(false);
  const [testUserEmail, setTestUserEmail] = useState('test@seatime.com');
  const [testUserPassword, setTestUserPassword] = useState('TestPassword123!');
  const [testUserName, setTestUserName] = useState('Test User');
  const [creatingUser, setCreatingUser] = useState(false);

  useEffect(() => {
    loadSummary();
  }, []);

  const loadSummary = async () => {
    try {
      console.log('[Reports] Loading summary from backend...');
      
      const summaryData = await seaTimeApi.getReportSummary();
      console.log('[Reports] Loaded summary:', summaryData);
      
      setSummary(summaryData);
    } catch (error) {
      console.error('[Reports] Error loading summary:', error);
      Alert.alert('Error', 'Failed to load report summary. Please try again.');
    }
  };

  const handleExportCSV = async () => {
    setLoading(true);
    try {
      console.log('[Reports] Exporting CSV report...');
      
      const csvContent = await seaTimeApi.downloadCSVReport();
      console.log('[Reports] CSV downloaded, length:', csvContent.length);
      
      // Save CSV to file system
      const fileName = `seatime_report_${new Date().toISOString().split('T')[0]}.csv`;
      const fileUri = `${FileSystem.documentDirectory}${fileName}`;
      
      await FileSystem.writeAsStringAsync(fileUri, csvContent, {
        encoding: FileSystem.EncodingType.UTF8,
      });
      
      console.log('[Reports] CSV saved to:', fileUri);
      
      // Share the file
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(fileUri, {
          mimeType: 'text/csv',
          dialogTitle: 'Export SeaTime Report',
          UTI: 'public.comma-separated-values-text',
        });
      } else {
        Alert.alert('Success', `Report saved to: ${fileName}`);
      }
    } catch (error) {
      console.error('[Reports] Error exporting CSV:', error);
      Alert.alert('Error', 'Failed to export report. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleShareReport = async () => {
    try {
      await Share.share({
        message: `SeaTime Tracker Report\n\nTotal Sea Time: ${summary?.total_hours.toFixed(1)} hours (${summary?.total_days.toFixed(1)} days)\n\nGenerated by SeaTime Tracker`,
      });
    } catch (error) {
      console.error('Error sharing report:', error);
    }
  };

  const handleSignOut = async () => {
    Alert.alert(
      'Sign Out',
      'Are you sure you want to sign out?',
      [
        {
          text: 'Cancel',
          style: 'cancel',
        },
        {
          text: 'Sign Out',
          style: 'destructive',
          onPress: async () => {
            try {
              console.log('[Profile] User signing out');
              await signOut();
              console.log('[Profile] Sign out successful');
            } catch (error) {
              console.error('[Profile] Error signing out:', error);
              Alert.alert('Error', 'Failed to sign out. Please try again.');
            }
          },
        },
      ]
    );
  };

  const handleCreateTestUser = async () => {
    if (!testUserEmail || !testUserPassword || !testUserName) {
      Alert.alert('Error', 'Please fill in all fields');
      return;
    }

    setCreatingUser(true);
    try {
      console.log('[Profile] Creating test user:', testUserEmail);
      const result = await seaTimeApi.createTestUser(testUserEmail, testUserPassword, testUserName);
      
      if (result.success) {
        Alert.alert(
          'Success',
          `Test user created successfully!\n\nEmail: ${testUserEmail}\nPassword: ${testUserPassword}\n\nYou can now sign in with these credentials.`,
          [
            {
              text: 'OK',
              onPress: () => setShowTestUserModal(false),
            },
          ]
        );
      } else {
        Alert.alert('Error', result.error || 'Failed to create test user');
      }
    } catch (error: any) {
      console.error('[Profile] Error creating test user:', error);
      Alert.alert('Error', error.message || 'Failed to create test user. Please try again.');
    } finally {
      setCreatingUser(false);
    }
  };

  const styles = createStyles(isDark);

  return (
    <View style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <View style={styles.headerTop}>
          <View>
            <Text style={styles.headerTitle}>Reports</Text>
            <Text style={styles.headerSubtitle}>MCA Compliant Sea Service Records</Text>
          </View>
          <View style={styles.headerButtons}>
            <TouchableOpacity
              style={styles.devButton}
              onPress={() => setShowTestUserModal(true)}
            >
              <IconSymbol
                ios_icon_name="person.badge.plus"
                android_material_icon_name="person-add"
                size={20}
                color={colors.primary}
              />
            </TouchableOpacity>
            <TouchableOpacity
              style={styles.signOutButton}
              onPress={handleSignOut}
            >
              <IconSymbol
                ios_icon_name="rectangle.portrait.and.arrow.right"
                android_material_icon_name="logout"
                size={20}
                color={colors.error}
              />
            </TouchableOpacity>
          </View>
        </View>
        {user && (
          <View style={styles.userInfo}>
            <IconSymbol
              ios_icon_name="person.circle.fill"
              android_material_icon_name="account-circle"
              size={16}
              color={isDark ? colors.textSecondary : colors.textSecondaryLight}
            />
            <Text style={styles.userEmail}>{user.email}</Text>
          </View>
        )}
      </View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
      >
        {/* Summary Cards */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Summary</Text>
          
          <View style={styles.summaryGrid}>
            <View style={[styles.summaryCard, styles.primaryCard]}>
              <IconSymbol
                ios_icon_name="clock"
                android_material_icon_name="schedule"
                size={32}
                color="#FFFFFF"
              />
              <Text style={styles.summaryValue}>
                {summary?.total_hours.toFixed(1) || '0.0'}
              </Text>
              <Text style={styles.summaryLabel}>Total Hours</Text>
            </View>
            
            <View style={[styles.summaryCard, styles.accentCard]}>
              <IconSymbol
                ios_icon_name="calendar"
                android_material_icon_name="calendar-today"
                size={32}
                color="#FFFFFF"
              />
              <Text style={styles.summaryValue}>
                {summary?.total_days.toFixed(1) || '0.0'}
              </Text>
              <Text style={styles.summaryLabel}>Total Days</Text>
            </View>
          </View>
        </View>

        {/* By Vessel */}
        {summary && summary.entries_by_vessel.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>By Vessel</Text>
            {summary.entries_by_vessel.map((item, index) => (
              <View key={index} style={styles.card}>
                <View style={styles.cardRow}>
                  <Text style={styles.cardTitle}>{item.vessel_name}</Text>
                  <Text style={styles.cardValue}>
                    {item.total_hours.toFixed(1)} hrs
                  </Text>
                </View>
              </View>
            ))}
          </View>
        )}

        {/* By Month */}
        {summary && summary.entries_by_month.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>By Month</Text>
            {summary.entries_by_month.map((item, index) => (
              <View key={index} style={styles.card}>
                <View style={styles.cardRow}>
                  <Text style={styles.cardTitle}>{item.month}</Text>
                  <Text style={styles.cardValue}>
                    {item.total_hours.toFixed(1)} hrs
                  </Text>
                </View>
              </View>
            ))}
          </View>
        )}

        {/* Export Actions */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Export</Text>
          
          <TouchableOpacity
            style={[styles.button, styles.primaryButton]}
            onPress={handleExportCSV}
            disabled={loading}
          >
            <IconSymbol
              ios_icon_name="document"
              android_material_icon_name="description"
              size={20}
              color="#FFFFFF"
            />
            <Text style={styles.buttonText}>
              {loading ? 'Exporting...' : 'Export CSV Report'}
            </Text>
          </TouchableOpacity>
          
          <TouchableOpacity
            style={[styles.button, styles.secondaryButton]}
            onPress={handleShareReport}
          >
            <IconSymbol
              ios_icon_name="share"
              android_material_icon_name="share"
              size={20}
              color="#FFFFFF"
            />
            <Text style={styles.buttonText}>Share Summary</Text>
          </TouchableOpacity>
        </View>

        {/* Info */}
        <View style={styles.infoCard}>
          <IconSymbol
            ios_icon_name="info.circle"
            android_material_icon_name="info"
            size={24}
            color={colors.primary}
          />
          <Text style={styles.infoText}>
            Reports are generated in MCA-compliant format for sea service testimonials. 
            CSV exports include all confirmed sea time entries with vessel details, dates, 
            and duration.
          </Text>
        </View>
      </ScrollView>

      {/* Test User Creation Modal */}
      <Modal
        visible={showTestUserModal}
        animationType="slide"
        transparent={true}
        onRequestClose={() => setShowTestUserModal(false)}
      >
        <View style={styles.modalOverlay}>
          <View style={[styles.modalContent, { backgroundColor: isDark ? colors.cardBackground : colors.card }]}>
            <View style={styles.modalHeader}>
              <Text style={styles.modalTitle}>Create Test User</Text>
              <TouchableOpacity
                onPress={() => setShowTestUserModal(false)}
                style={styles.modalCloseButton}
              >
                <IconSymbol
                  ios_icon_name="xmark"
                  android_material_icon_name="close"
                  size={24}
                  color={isDark ? colors.text : colors.textLight}
                />
              </TouchableOpacity>
            </View>

            <View style={styles.modalBody}>
              <Text style={styles.inputLabel}>Email</Text>
              <TextInput
                style={styles.input}
                value={testUserEmail}
                onChangeText={setTestUserEmail}
                placeholder="test@seatime.com"
                placeholderTextColor={isDark ? colors.textSecondary : colors.textSecondaryLight}
                keyboardType="email-address"
                autoCapitalize="none"
              />

              <Text style={styles.inputLabel}>Password</Text>
              <TextInput
                style={styles.input}
                value={testUserPassword}
                onChangeText={setTestUserPassword}
                placeholder="TestPassword123!"
                placeholderTextColor={isDark ? colors.textSecondary : colors.textSecondaryLight}
                secureTextEntry
              />

              <Text style={styles.inputLabel}>Name</Text>
              <TextInput
                style={styles.input}
                value={testUserName}
                onChangeText={setTestUserName}
                placeholder="Test User"
                placeholderTextColor={isDark ? colors.textSecondary : colors.textSecondaryLight}
              />

              <TouchableOpacity
                style={[styles.button, styles.primaryButton, creatingUser && styles.buttonDisabled]}
                onPress={handleCreateTestUser}
                disabled={creatingUser}
              >
                <IconSymbol
                  ios_icon_name="person.badge.plus"
                  android_material_icon_name="person-add"
                  size={20}
                  color="#FFFFFF"
                />
                <Text style={styles.buttonText}>
                  {creatingUser ? 'Creating...' : 'Create Test User'}
                </Text>
              </TouchableOpacity>

              <View style={styles.infoCard}>
                <IconSymbol
                  ios_icon_name="info.circle"
                  android_material_icon_name="info"
                  size={20}
                  color={colors.primary}
                />
                <Text style={styles.infoText}>
                  This will create a test user account that you can use to sign in and test the app. 
                  Save the credentials to sign in later.
                </Text>
              </View>
            </View>
          </View>
        </View>
      </Modal>
    </View>
  );
}

const createStyles = (isDark: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: isDark ? colors.background : colors.backgroundLight,
    },
    header: {
      padding: 20,
      paddingTop: Platform.OS === 'android' ? 48 : 20,
      backgroundColor: isDark ? colors.cardBackground : colors.card,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? colors.border : colors.borderLight,
    },
    headerTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
    },
    headerTitle: {
      fontSize: 28,
      fontWeight: '700',
      color: isDark ? colors.text : colors.textLight,
    },
    headerSubtitle: {
      fontSize: 14,
      color: isDark ? colors.textSecondary : colors.textSecondaryLight,
      marginTop: 4,
    },
    headerButtons: {
      flexDirection: 'row',
      gap: 8,
    },
    devButton: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: isDark ? 'rgba(0, 119, 190, 0.1)' : 'rgba(0, 119, 190, 0.1)',
    },
    signOutButton: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: isDark ? 'rgba(255, 59, 48, 0.1)' : 'rgba(255, 59, 48, 0.1)',
    },
    userInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 12,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: isDark ? colors.border : colors.borderLight,
    },
    userEmail: {
      fontSize: 13,
      color: isDark ? colors.textSecondary : colors.textSecondaryLight,
      fontWeight: '500',
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      padding: 16,
      paddingBottom: 100,
    },
    section: {
      marginBottom: 24,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: isDark ? colors.text : colors.textLight,
      marginBottom: 12,
    },
    summaryGrid: {
      flexDirection: 'row',
      gap: 12,
    },
    summaryCard: {
      flex: 1,
      borderRadius: 12,
      padding: 20,
      alignItems: 'center',
      boxShadow: '0px 2px 8px rgba(0, 119, 190, 0.15)',
      elevation: 3,
    },
    primaryCard: {
      backgroundColor: colors.primary,
    },
    accentCard: {
      backgroundColor: colors.accent,
    },
    summaryValue: {
      fontSize: 32,
      fontWeight: '700',
      color: '#FFFFFF',
      marginTop: 12,
    },
    summaryLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: '#FFFFFF',
      marginTop: 4,
    },
    card: {
      backgroundColor: isDark ? colors.cardBackground : colors.card,
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: isDark ? colors.border : colors.borderLight,
      boxShadow: '0px 2px 8px rgba(0, 119, 190, 0.1)',
      elevation: 2,
    },
    cardRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    cardTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: isDark ? colors.text : colors.textLight,
    },
    cardValue: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.primary,
    },
    button: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: 10,
      gap: 8,
      marginBottom: 12,
    },
    primaryButton: {
      backgroundColor: colors.primary,
    },
    secondaryButton: {
      backgroundColor: colors.accent,
    },
    buttonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '600',
    },
    infoCard: {
      flexDirection: 'row',
      backgroundColor: isDark ? colors.cardBackground : colors.card,
      borderRadius: 12,
      padding: 16,
      gap: 12,
      borderWidth: 1,
      borderColor: colors.primary,
      marginTop: 8,
    },
    infoText: {
      flex: 1,
      fontSize: 14,
      color: isDark ? colors.textSecondary : colors.textSecondaryLight,
      lineHeight: 20,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalContent: {
      width: '100%',
      maxWidth: 500,
      borderRadius: 16,
      boxShadow: '0px 4px 16px rgba(0, 0, 0, 0.2)',
      elevation: 5,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? colors.border : colors.borderLight,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: isDark ? colors.text : colors.textLight,
    },
    modalCloseButton: {
      padding: 4,
    },
    modalBody: {
      padding: 20,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: isDark ? colors.text : colors.textLight,
      marginBottom: 8,
      marginTop: 12,
    },
    input: {
      backgroundColor: isDark ? colors.background : colors.backgroundLight,
      borderWidth: 1,
      borderColor: isDark ? colors.border : colors.borderLight,
      borderRadius: 10,
      padding: 14,
      fontSize: 16,
      color: isDark ? colors.text : colors.textLight,
    },
    buttonDisabled: {
      opacity: 0.5,
    },
  });
